# API SEQUENTIAL TESTING OF CRUD OPERATIONS


# CREATE(C)

### 1
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Johnson Ugo Daniel",
    "subscribedToChannel": "KNUST"
}

### 2
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "John Quaye",
    "subscribedToChannel": "Chemu SHS"
}

### 3
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Emmanuel Owusu",
    "subscribedToChannel": "SmartGuys"
}





# READ(R)

### 1 (Read all Subscribers)
GET http://localhost:3000/subscribers

### 2 (Read specific Subscriber)
GET http://localhost:3000/subscribers/?id=6738f8a1c377173b1720638c




# UPDATE(U)
### 1
PATCH http://localhost:3000/subscribers/6738fa65537cd0e33e3591e4
Content-Type: application/json 

{
    "name": "Judith",
    "subscribedToChannel": "TEDx" 
}





# DELETE(D)
### 1
DELETE http://localhost:3000/subscribers/6738fa65537cd0e33e3591e4